#include <avr/io.h>
.text


.global slowDivisionUint8
slowDivisionUint8:
  // TODO: uint8_t slowDivisionUint8(uint8_t a, uint8_t b)
  ret


.global cStringLength
cStringLength:
  // TODO: uint8_t cStringLength(const char aString[])
  ret

.global sumArray
sumArray:
  // TODO: uint16_t sumArray(uint8_t a[], uint8_t length)
  ret


.global greaterThanOrEqualUInt16
greaterThanOrEqualUInt16:
  // TODO: bool greaterThanOrEqualUInt16(uint16_t a, uint16_t b)
  ret


.global slowDivisionUint16
slowDivisionUint16:
  // TODO: uint16_t slowDivisionUint16(uint16_t a, uint16_t b)
  ret


.global avgArray
avgArray:
  // TODO: uint16_t avgArray(uint8_t a[], uint8_t length)
  ret


